### ISSUE TITLE
More verbose code

### ISSUE THREAD

**Issue by ahartikainen** [stan-dev/cmdstanpy#13]
#### Summary:

What do you think if the code would be a bit more verbose?

Now there are many locations where I'm not totally certain what some values should be 

    # this is example
    _, k, v = p
    c, v = ... 

    _, header, tail = p

or some things could be even more verbose. I'm not saying that we fill the code with comments, but just have descriptive variable names (in some places).

**Comment by mitzimorris** [comment]
is this an evergreen issue?  just merged https://github.com/stan-dev/cmdstanpy/pull/21
other than loop indices, variable names are succinct but not cryptic.

**Comment by bob-carpenter** [comment]
The easiest code to read has short variable names with localized scope, descriptive function names, and no in-code doc.  I also like complete API doc, but that doesn't help with code readability.

Long variable names are a form of code clutter that can make code hard to read.   We like `log(sqrt(2 * pi))` over `natural_logarithm(square_root(2 * circumference_of_unit_circle))` in part because it's easier to read.  But only if we can easily figure out what function`sqrt` is, can guess the base of `log`, and know what `pi` is.  Otherwise, we need more descriptive names.  Even then, shorter is better.

**Comment by maedoc** [comment]
> variable names are succinct but not cryptic

agreed with recent merger, I just glanced briefly through; the few short variable names are only very locally scoped, with `fd` for an open file being an exception, but that's conventional enough in my opinion to not count.  I would suggest considered this issue closed.
