### ISSUE TITLE
Main purpose of the library

### ISSUE THREAD

**Issue by ahartikainen** [stan-dev/cmdstanpy#14]
Hi, what should be the main purpose of this library.

Is it just a helper library to call cmdstan with a pythonic interface? How important is it to read output csv and handle csv information?

How much do you want to add extra functionality on top of that?

I know there is the wiki/docs/specs somewhere, but I'm just asking for your general opinion.

I made some points, some are probably wrong:

    [+]  0. Automatic setup of the CmdStan?
    [+]  1. Text to textfile
    [+]  2. Translate stan --> hpp with stanc
    [+]  3. Compile hpp
    [/]  4. Data from python -> text file
    [+]  5. sample/vb/etc
    [ ]  6. Read output?
    [+]  7. Call stansummary
    [+]  8. Call/check diagnostics
    [-]  9. plotting
    [-] 10. analyze results

Meaning:

    [+] this lib
    [/] maybe this lib?
    [ ] maybe or maybe not?
    [-] not this lib

**Comment by ahartikainen** [comment]
For reading the input I don't mean that we should not have that functionality, I'm just thinking that should we encourage our users to use it or interact some other way?

Also, what is the order if nD samples after reading? F-order like in PyStan3?

    *shape, draw, chain

Just making sure that this is correct. I will make a helper reader for ArviZ for these samples after (/or before we have first release); That reader will be based on either reading csv files with `from_cmdstan` or then `from_dict` with suitable numpy reshaping magic.

**Comment by seantalts** [comment]
> I know there is the wiki/docs/specs somewhere, but I'm just asking for your general opinion.

For reference, there's an ideal functional [spec](https://github.com/stan-dev/design-docs/blob/master/designs/0002-cmdstanpy_func_spec.md) here that goes as low-level as what some of the methods / functions should be called and what parameters they should take in. But that doesn't answer most of your questions. 

@mitzimorris and I got some feedback from @mandel and @gbdrt, they mentioned how nice it would be if this library could manage a cmdstan install/clone for the user (though also nice to keep it configurable if need be). I would vote that it would be nice if probably 0-8 on your list were all handled by CmdStanPy.

**Comment by maedoc** [comment]
the lib from which this codebase is derived intended to hit all ten of those (cf https://pycmdstan.readthedocs.io), but the spec for cmdstanpy is more limited in scope and less opinionated (eg pycmdstan computes PSIS LOO automatically but not everyone uses that etc)

I find it useful, for clarity of a workflow, to have good integration with some validation and visualization tool, so if arviz is the tool of choice, it’s worth massaging things to make them work together, IMO. 

I don’t understand the question about F order, since the columns of the CSV provide the layout.. and NumPy makes it transparent. Can you clarify and possibly look at the unit test for parsing matrix output?

**Comment by maedoc** [comment]
> then from_dict with suitable numpy reshaping magic

Ah maybe I misunderstood your question because the csv parser here already reshapes the arrays appropriately [here](https://github.com/stan-dev/cmdstanpy/blob/master/cmdstanpy/io.py#L128)

**Comment by ahartikainen** [comment]
The csv has data in F-order, but that is for one chain.

PyStan3 (actually Stan3) and ArviZ use different order

Stan3:

    *shape, draw, chain

ArviZ

    chain, draw, *shape

(and it is not nice for user to do those reshaping manually).

ArviZ is currently Python3 only, so what we could do is to fork it for Python 2 then "freeze" the development.

**Comment by ahartikainen** [comment]
Ok, here I meant Stan3 == (RStan3, PyStan3)
See 

https://github.com/stan-dev/stan/wiki/User-Interface-Guidelines-for-Developers


if the parameter is originally a scalar, on the interface side it acts like a 3D array that is 1 x chains x iterations
if the parameter is originally a (row) K-vector, on the interface side it acts like a 3D array that is K x chains x iterations
if the parameter is originally a matrix, on the interface side it acts like like a 4D array that is rows x cols x chains x iterations
if the parameter is originally a std::vector of type foo, on the interface side it acts like a multidimensional array with dimensions equal to the union of the std::vector dimensions, the foo dimensions, chains, and iterations


https://discourse.mc-stan.org/t/rstan3-and-pystan3-interface/666

**Comment by mitzimorris** [comment]
agree with @seantalts - CmdStanPy should handle 1-8 on your list.

The goals are outlined in the functional spec -

* ease up update with each new Stan release - makes new features available to Python users right away
* BSD license (PyStan is GPL and therefore off limits to many potential users)
* minimal install requirements - can be used by folks who don't have any admin privileges
* efficient

For downstream plotting, use of pandas would facilitate creating long-form data for python equivalent of ggplot.  More importantly, it would allow ragged data structures.

If we only use numpy and ndarrays, then the data must be rectangular - same number of draws for all chains.  The information in a sample should be stored in column order (F-order), and within a column, the draws are grouped by chain, in iteration order.

**Comment by maedoc** [comment]
> Efficiency is a key concern when going from the set of CmdStan csv files to an in-memory data structure that holds the sample - the conversion should only be done once

In the current code, the conversion is only done once, but after the process exits.  I toyed with a threaded FIFO implementation which parses samples as they are written by Stan which makes "total turn around time" lower especially for larger models.  On hyperthreaded cores, there shouldn't be any penalty for the Stan processes.  If this is interesting to others, it might be worth ironing out the bugs and making the default implementation.

> it would allow ragged data structures

does Stan output ragged/sparse data? `cmdstanpy.io.parse_csv` will fail on non rectangular data in CSV..

**Comment by ahartikainen** [comment]
`CmdStan csv files to an in-memory data structure`

How important this is? Like 100k parameters with pandas takes minutes, with csv reader probably a bit longer.

**Comment by maedoc** [comment]
SSDs are nice, but I use Stan frequently on shared NFS storage on HPC, and using a FIFO to avoid a round trip across the network is helpful when the equivalent CSV is many GB.

**Comment by ahartikainen** [comment]
Yeah, that is true, 

ArviZ currently creates an empty array and fill it based on csv header. So "sparse" structures have `nan` where there is no data. It does not support real sparse/ragged data. Not sure if Stan supports real sparse / ragget structures.

**Comment by ahartikainen** [comment]
@maedoc I think that reading samples as they come could also use tqdm to show progressbar?

**Comment by mitzimorris** [comment]
> does Stan output ragged/sparse data? cmdstanpy.io.parse_csv will fail on non rectangular data in CSV.

no Stan doesn't - what we've got now is most definitely rectangular.

at some future point, were Stan to introduce a time-based as opposed to iteration-based mechanism for controlling the sampler, then different chains would produce different number of draws.  but for now, rectangular is fine.

**Comment by mitzimorris** [comment]
let's look at the use cases for downstream analysis:

- output validation - need to know chain, iteration in order to compute R-hat, N_eff, and per-chain diagnostics

- computing with the posterior  - information from all chains, all iterations is used, information access is per parameter, i.e., per column of csv output

in order to address both use cases, the draws should be ordered by chain, iteration.
however, we could just use cmdstan's `stansummary` and `diagnose` utilities for validation.
otherwise we just need the draws.

the trade-off is between making this as lightweight as possible vs. generality - for generality - should downstream analysis want to recover chain, iteration information, then you'd need to assemble the draws accordingly.  a single ndarray of just the draws with meta-information to give you offsets by chain, iteration would work here.

does this make sense?

**Comment by maedoc** [comment]
> trade-off is between making this as lightweight as possible vs. generality

I don't think "lightweight as possible" is a useful metric, when we're talking about an already tiny library intended to be used with a scientific Python stack (conda envs measure in hundred of MB or more these days).  It's worth considering that Python users usually expect a "Pythonic" API even when it requires a few more lines of implementation, since it makes their own scripts & notebooks cleaner by avoiding plumbing work, e.g. the `RunSet.R_hats` property is a shortcut for collecting csv filenames, running stansummary, parsing results into an ndarray, even though all that can be done by hand, tweaked for specific use case, etc.

> in order to address both use cases, the draws should be ordered by chain, iteration

Tthe chain, iteration and so on is already available from the current API, as well as the concatenated sample ndarrays, in order mentioned above (n_chain, n_iter, ...), so I think this is a non issue until a counter example is identified.

**Comment by mitzimorris** [comment]
going back to one of Ari's initial questions:

> Is it just a helper library to call cmdstan with a pythonic interface? How important is it to read output csv and handle csv information?

yes, it is a helper library to call cmdstan. 

is the interface pythonic?  it depends - I honestly don't know what people mean by pythonic.

the spec lists these points under "design considerations"
https://github.com/stan-dev/design-docs/blob/master/designs/0002-cmdstanpy_func_spec.md

 - Choices for naming and structuring objects and functions should reflect the Stan workflow.
 - Data structure used for posterior sample facilitates downstream analysis.
   + is memory efficient - avoids making copies of big data.
   + provides fast access for per-parameter, per-chain information.

on the latter of these two point, agreed that the current implementation assembles the csv files in chain, iter order, so it's OK.

the set of classes and standalone functions listed in the functional spec reflect the first design goal:  a clear reflection of the Stan workflow.

**Comment by maedoc** [comment]
most points on scope have been addressed and @mitzimorris ' recent PR brought the code a lot closer to the spec.  a remaining issue for my workflow was viz, so I opened #26 for Arviz.  I think this issue could be closed now.

**Comment by mitzimorris** [comment]
closing.
