### ISSUE TITLE
sampling argument names - again!  warmup_iters, sampling_iters don't match cmdstan

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/cmdstanpy#154]
#### Summary:
CmdStanPy and CmdStanR should find a good consistent names for these and they should be updated for CmdStan and the semantics must be the same everywhere.

#### Description:
in CmdStan, total number of iterations is num_warmup + num_samples
CmdStanPy and CmdStanR should do the same thing.

there is noise from the fact that RStan does things differently and PyStan follows RStan.

#### Additional Information:
Provide any additional information here.

**Comment by ahartikainen** [comment]
PyStan should follow CmdStan

**Comment by jgabry** [comment]
Here are a two other differences I noticed in argument names (CmdStan vs CmdStanPy): 

* init vs inits
* max_depth vs max_treedepth

I actually prefer the names inits and max_treedepth that are in CmdStanPy but if the idea is to follow CmdStan then maybe we use the inferior names for now until CmdStan has better ones?

**Comment by jgabry** [comment]
Here's where CmdStanR currently differs from CmdStanPy in terms of argument names. In R what we've been doing is trying to either match CmdStan exactly or (when the argument doesn't exist, like for number of chains) be consistent with CmdStan naming conventions (however imperfect they may currently be):

```r
# not in CmdStan but consistent with naming convention
num_chains 
num_cores

# same as CmdStan
num_samples
num_warmup
init
max_depth
stepsize
```

CmdStanR also has a `save_diagnostics` (boolean), which replaces CmdStan's `diagnostic_file` because it doesn't make sense to make user's specify a file path when we can use temp files and then let them save them via method `save_diagnostic_files()`, just like `save_output_files()`. 

@bbbales2 also add an argument `inv_metric` that allows specifying the inverse metric directly as an R object (e.g. vector/matrix) instead of via a file (although we do also have CmdStan's standard `metric_file` argument)

**Comment by mitzimorris** [comment]
now addressed by https://github.com/stan-dev/cmdstanpy/issues/221
