### ISSUE TITLE
Consider using hash of source rather than mtime to invalidate the exe file.

### ISSUE THREAD

**Issue by SiegeLordEx** [stan-dev/cmdstanpy#157]
#### Summary:
When storing the source file inline (like https://github.com/stan-dev/cmdstanpy/issues/102#issuecomment-520237832), the CmdStanPy will constantly recompile the model because the source file will be re-written each time the Python source is ran. To avoid this, a user could check that the .stan file already exists or do some hash check to avoid re-writing the file, letting the current CmdStanPy's mtime-based caching logic do its thing. I am suggesting changing CmdStanPy to base its cache invalidation logic on the hash of the .stan file.

I.e. upon compilation, CmdStanPy would store the hash of the source file somewhere, and next time `compile` is called, it would check the hash of the source against what is stored on disk and recompile if there's a mismatch.

**Comment by ahartikainen** [comment]
Hi, thanks for the issue.

I'm not sure if this is something we can / want to do. `PyStan 3` will have this feature.

`CmdStanPy` is a light wrapper around CmdStan, so this would mean that we start to keep db on files etc.

We probably could add example to show how user can handle these situations

```
import os
stanfile = "path/to/file.stan"
exe = os.path.splitext(stanfile)
if not os.path.exists(exe):
    exe = None
...
```

**Comment by mitzimorris** [comment]
> I'm not sure if this is something we can / want to do.

agreeing with Ari's comment above - for exactly the same reasons - CmdStanPy requires everything to be a file because CmdStan operates on files.

the underlying issue for #102 is that when presenting a model via a Jupyter notebook, we want to be able to both show the model and compile and run it via CmdStanPy.  but the primary object is the on-disk file.  this was solved by adding method `code` to the CmdStanModel class - https://cmdstanpy.readthedocs.io/en/latest/api.html#cmdstanpy.CmdStanModel.code
