### ISSUE TITLE
Setting CMDSTAN environment variable causes test to fail

### ISSUE THREAD

**Issue by wesbarnett** [stan-dev/cmdstanpy#188]
#### Summary:
cmdstanpy properly finds cmdstan when `CMDSTAN` environment is set, but one test does fail. 

#### Description:
There is a test to see that cmdstan is located at `~/.cmdstanpy/cmdstan-<version>`, but a user can change the location of cmdstan by setting `CMDSTAN` environment variable.

https://github.com/stan-dev/cmdstanpy/blob/f20c9bb9002387dfc662fe84d98d24f9df1850e8/test/test_utils.py#L35-L40

#### Current Version:
master

**Comment by ahartikainen** [comment]
Yeah, this should be removed or add some fixture which would say it is ok to fail this test unless TRAVIS (or something similar) is not set

**Comment by mitzimorris** [comment]
> Yeah, this should be removed or add some fixture which would say it is ok to fail this test unless TRAVIS (or something similar) is not set

the problem is not TRAVIS - the problem is the test doesn't take into account logic in the code

 https://github.com/stan-dev/cmdstanpy/blob/edd34ed072cfb3cc30f0a9d8d8df2a7fd267d529/cmdstanpy/utils.py#L179-L195

there should be a test for when os.environ['CMDSTAN'] is set, and a test for when it isn't set.
