### ISSUE TITLE
Add a more memory efficient access to chain's samples

### ISSUE THREAD

**Issue by SiegeLordEx** [stan-dev/cmdstanpy#218]
#### Summary:
I'd like for an alternate api to `CmdStanMCMC.sample` that doesn't load every single sample into memory.

#### Description:
Today, `CmdStanMCMC.sample` fetches the totality of the samples (sans the warmup) into a single numpy array. There are two issues with this:

- It's very memory inefficient if all you'll be doing is computing mean/variance/order statistics.
- It's very slow, since the loading is not parallelized.

I'd like an API that either provides a streaming access to the chain's samples, or at the very least, restricts the samples returned to a single chain (reducing memory usage by a factor of 4 in the typical case, or more depending on the number of chains).

I guess in the ideal case, the access to samples would be done through `mmap`/`numpy.memmap`, but that seems like it's far out (https://github.com/stan-dev/stan/issues/519).

#### Current Version:
0.0.8

**Comment by bob-carpenter** [comment]
CmdStan itself currently streams out in an ASCII CSV format.  It would probably be pretty easy to not read that in.  Providing easy access to that CSV file is another story.

Plans are in the works to add JSON and possibly some kind of binary output.  I'm afraid that still wouldn't be an ideal memory map format.  

We need to keep the information about multiple chains in order to do convergence diagnostics.  But after that, they can all be combined for downstream inference.

**Comment by ahartikainen** [comment]
We could add that option.

So, it would not read in the data (csv), maybe it would only parse the header information.

But for csv access, maybe we could have a dask interface?

https://dask.org/

**Comment by mitzimorris** [comment]
by specifying the `output_dir` option to the sampler, which puts the csv files to a known location, allowing users to build interfaces which get the sampler outputs as they are written to disk.

**Comment by fcostin** [comment]
here's an instance illustrating memory efficiency reported from discourse, where a user is calling cmdstanpy indirectly through `ArviZ`:  https://discourse.mc-stan.org/t/is-there-a-different-less-memory-intensive-way-to-plot-a-posterior-predictive-check/25230

in this case there's a fair chance that the user has unintentionally/accidentally requested a huge number of columns, but it does also serve as an illustrative example of how the current `ArviZ -> cmdstanpy` integration fails to be memory efficient.

In terms of `cmdstanpy` usability, it may be difficult for users or developers to have success with Stan and use access samples `cmdstanpy` samples efficient way if `cmdstanpy` does not offer a documented and easy to use python API for doing that.

One idea could to be to refactor `_assemble_draws` and expose an `iterdraws` type function to the user that would allow them to easily stream samples off disk without buffering them all into RAM, but still have cmdstanpy help parse and interpret the samples.

E.g. it might look something like the following -- also supporting the optional `vars` argument from the `draws_xr` method that allows the user to indicate a subset of columns they care about:

```python
from typing import Generator, List


def iterdraws(self, chain: int, vars: Union[str, List[str], None] = None) -> Generator[int, List[float], None]:

    selected_column_indices = figure_out_col_indices_from_vars(vars)  # TODO. draws_xr method already does something akin to this.
    
    with open(self.runset.csv_files[chain], 'r') as fd:
        line = fd.readline().strip()
        # TODO skip over initial header line, comments, etc..
        sampling_iter_start =  None  # TODO
        num_draws = None  # TODO
        
        for i in range(sampling_iter_start, num_draws):
            line = fd.readline().strip()
            xs = line.split(',')
            yield [float(xs[j]) for j in selected_column_indices]
```

**Comment by WardBrian** [comment]
Such an iterdraws method would be a pretty easy extension (assuming we did as your e ample does and only provide it for one chain at a time). 

I’m not terribly familiar with the internals of Arviz but would that help this issue? I believe that most of these tools ultimately require you to either have all the data in memory or use an out of core scheduler like Dask

**Comment by fcostin** [comment]
@WardBrian thanks for taking a look at it

> I’m not terribly familiar with the internals of Arviz but would that help this issue? I believe that most of these tools ultimately require you to either have all the data in memory or use an out of core scheduler like Dask

I am not familiar with Arviz either.  it wouldn't be surprising if it works as you suggest, so it would require changes in multiple libraries.

i guess the argument could be if cmdstanpy makes it obvious how to do things in a memory efficient way this year, maybe in a year or twos time support for more memory efficiency could surface in other libraries that depend upon cmdstanpy

in principle, if the user was wanting to do something such as raster a 2D plot of some marginal distribution, then this would only require memory proportional to the number of pixels in the image, each sample from Stan could be directly projected down onto the plot coordinate space and stamped onto an image buffer.

**Comment by WardBrian** [comment]
I suppose it’s possible. I do want to clarify that this isn’t really a question of memory efficiency: cmdstanpy is using exactly as much memory as it takes to represent that many floating point numbers (if you multiply the samples, chains, and columns times 8 and convert to gigabytes it’s the exact number the memory error is reporting)

The issue is really about laziness vs greediness in how that memory is allocated. Getting that right is complicated, and there will always be cases where the only correct thing to do actually is to load all ~300 gigs into RAM at once. In a lot of other cases, we can do more streaming of rows or only selectively reading in certain columns, but the trade off cost there is you’re constantly hitting disk I/O. On some machines, that’s a lot pricier than the RAM cost. So, any real solution needs to be able to do either to cover everybody’s use cases

I’ve been meaning to look into if we would be able to have the xarray method return a dask-backed array which would already cover a lot of the use cases for this, but xarray/dask work a lot better with binary data formats than with something like csv, especially the wonky CSVs we use

**Comment by fcostin** [comment]
you make a good point that in many use cases it can be necessary to load the entire dataset into RAM.

perhaps there are two different issues that i've conflated by commenting on this older ticket:

(1) use cases where it is necessary to process all the data in all the rows, where the total size of data is larger than RAM -- then the question of greedily or lazily loading the rows, or being able to stream them (as in the original issue description) 
(2) use cases where a computation depends on a subset of columns only -- different to the original use case described in this issue. I can see a few instances of this use case in how the ArviZ library is trying to use cmdstan & cmdstanpy .   there are n + m columns in each sample and and ArviZ only wants to load n of the total n+ m columns.
