### ISSUE TITLE
use ProcessPoolExecutor not ThreadPoolExecutor to run chains in parallel

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/cmdstanpy#248]
#### Summary:

File `cmdstanpy/model.py` currently uses ThreadPoolExecutor; change to ProcessPoolExecutor, per discussion here:  https://stackoverflow.com/questions/51828790/what-is-the-difference-between-processpoolexecutor-and-threadpoolexecutor

#### Description:
As part of implementation, run timing tests to show that this speeds things up.

**Comment by ahartikainen** [comment]
What problem would this solve? The python side processing?

**Comment by mitzimorris** [comment]
I think this would speed up parallel execution of the chains, since for complex models, most of the processing time is spent calculating gradients - I would say that Stan programs are CPU-bound.  always testing on the bernoulli model might make it seem otherwise.

that's why I think we should swap in ProcessPoolExecutor and then fit a big-ish model to see if there's a difference.

**Comment by ahartikainen** [comment]
We call subprocess so python threads don't affect CmdStan.

**Comment by maedoc** [comment]
A thread pool is the right way to go since everything in the Python process is I/o bound and the computation is happening in child processes. 

Process pool is or at least was a precarious proposition on Windows, so this change would most likely be a net negative, unless CSV is consuming an enormous amount of time.

That said, it would be cheap to use joblib to distribute the work and let the user decide what sort of pool they want.

**Comment by mitzimorris** [comment]
many thanks to both of you for your input - glad to know we're doing the right thing.
