### ISSUE TITLE
add option to `save_csvfiles` for filename prefix

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/cmdstanpy#254]
#### Summary:
To facilitate distributed processing, the `save_csvfiles` method should be able to add a prefix to the
filename, so that per-node csvfiles from a cluster job can all be written to the same centralized filesystem
without filename conflict.

#### Description:
From discussion on the forums:

> I am working on a distributed computing pool and wish to run many independent instances of an analysis. If these jobs are submitted at the same time, I will get file-name clashes and some results will be overwritten.

https://discourse.mc-stan.org/t/specifying-output-file-names/16345

#### Additional Information:

Proposal for argument `prefix` is to preserve information:  model, timestamp, chain - I consider this useful for managing the analysis process, which can be very messy.  Also, easy to implmenet. Discuss?

**Comment by mtwest2718** [comment]
I support the proposal to have a `prefix` argument, as long as it can be an integer. Because sampling jobs are independent and may be submitted to separate nodes simultaneously, two or more jobs may produce csvs with the same file name. Being able to include a prefix will prevent the filename clash while preserving the preferred naming scheme.

Also I want to explain a little better how my workflow management system (WMS) operates with CmdStan on a distributed file system.
1. WMS transfers executable and input data files to htcondor directory from Submit machine to Execute machine.
2. CmdStan transfers data to /tmp directory on Execute machine and begins sampling. 
3. CmdStan copies back streamed CSV file back to htcondor directory on Execute machine.
4. WMS copies desired (i.e. named) output files to $HOME directory on Submit machine.

Attached is an overly simplistic diagram of the above.
[cmdstan_htcondor.pdf](https://github.com/stan-dev/cmdstanpy/files/4872273/cmdstan_htcondor.pdf)

**Comment by mtwest2718** [comment]
**Related Question:**
Is the automatic & required transfer of files to `/tmp` before sampling a default feature in base CmdStan? 

Doing this makes it difficult to use the streamed CSV output as a checkpoint file if a sampling job is for some reason interrupted before completing.

**Comment by mtwest2718** [comment]
### Alternative Proposal
Knowing the filenames and directories at submit time allows for clearer control over a workflow, particularly when a workflow management system (WMS) is handling file transfers of results (or checkpoints) from an execute node. I also believe the changes below will have minimal impact on existing practices when developing locally.   

- **File Basename:** `output_basename` option that enables one to redefine the basename of the output file from the default. If the option is not given, it will use the default  of `ProgramName_DateTime`. For either condition, the chain # will be appended to the end of the filename. 
- **Output Directory:** Use the `output_dir` to specify where one wants the program to run the sampler rather than an auto-generated temp directory. If a directory isn't specified, run it in the current working directory.
- **Metadata:** The paths in [Runset](https://cmdstanpy.readthedocs.io/en/latest/api.html#runset)`.csv_files` should be an accessible attribute of the `CmdStanMCMC` [object](https://cmdstanpy.readthedocs.io/en/latest/api.html#cmdstanmcmc).
- **Streaming File Extension:** Rather using a random character string to identify the streaming csv output, use the extra extension `.ckpt`

**Comment by mitzimorris** [comment]
the use of tempfiles and the naming conventions are set up the way they are to facilitate the model development process, which is where developers spend most of their time, and to keep data runs distinct.  these defaults address a number of problems that I've seen when trying to teach Stan and when doing ongoing analysis with collaborators on their data.  your assessment of the impact of your proposal is based on your experience; I disagree.

adding a prefix option which can be used for node or any other kind fo id is definitely needed and will be added.

**Comment by mtwest2718** [comment]
Leaving the default method for when Stan is used for teaching &/or development is reasonable and I have no objection to that.

The thing is that these are not the only use-cases for CmdStan and the current file-name management is a roadblock to building automated workflows. A comprise would be exposing the `.csv_files` attribute of the various `CmdStan` objects, allowing users to know & adjust the filename if they see fit without having to add more command line options to the interface.

**Comment by mitzimorris** [comment]
you have complete control over the output directory, and the addition of node prefix will allow you to track all files.
the filenames are available as property `csv_files`

**Comment by mitzimorris** [comment]
Perhaps there's some confusion of how CmdStanPy creates and names output files.
The `sample` and other functions that expose CmdStan methods only write to temp directory if no `output_dir` argument is specified, the files are not written to tmp and then moved once sampling is completed.

In setting up the filename template as '<model_name>-<YYYYMMDDHHMM>-<chain_id>', the intent was to make the timestamp not very granular at all, so that a simple `ls` command would return all chains from a run in consecutive order, allowing for multiple runs to co-exist on disk - but perhaps that's too much of a development mindset and it would be better to make the template be '<model_name>-<chain_id>-<YYYYMMDDHHMM>' and to hell with `ls` sort order.

Note also, that the user has control over the chain ids - to run a thousand chains, it would be possible to distribute these requests across a cluster by sending along the seed and the slice of chain ids when distributing sample jobs across the cluster.  I think that this would be sufficient for the distributed cluster use case, especially the specified output dir is on a shared filesystem available to all cluster nodes, especially since my understanding is that the sampler processes are generally CPU bound, not IO bound.

**Comment by mitzimorris** [comment]
https://github.com/stan-dev/docs/pull/253 addreses this issue - it will result in a set of unique output file names and also do the right thing when running multiple chains using a cluster.
