### ISSUE TITLE
Support for pedantic mode

### ISSUE THREAD

**Issue by Christopher22** [stan-dev/cmdstanpy#307]
The current version of cmdstanpy does not support the pedantic mode [recently introduced in Cmdstan](https://statmodeling.stat.columbia.edu/2020/08/21/cmdstan-2-24-1-is-released/). As it is merely expressed as a simple flag "--warn-pedantic" in STANCFLAGS, supporting it should not be that complicated. I would volunteer in implementing it.

**Comment by cwindolf** [comment]
I am new to cmdstanpy, but I think that one way to do it would be a one-line change in `cmdstanpy/compiler_opts.py`:
```
STANC_OPTS = [
    'O',
    'allow_undefined',
    'use-opencl',
    'warn-pedantic', # the new line
    'warn-uninitialized',
    'include_paths',
    'name',
]
```
Then I can ask for pedantic mode in Python with:
```
model = CmdStanModel(stan_file="model.stan", stanc_options={"warn-pedantic": 1})
```
Not sure if this is the best way, but it works for me and just helped me debug my model. I'd be happy to submit a PR, but I can't find any guide to contributing to this project. Are there conventions for submitting PRs to cmdstanpy?

**Comment by mitzimorris** [comment]
we love submissions!

a good PR has unit tests.
all PRs are checked by both pylint and flake8 - config is here:  https://github.com/stan-dev/cmdstanpy/blob/3c1745560953cd3092f642b6781911456d9648f4/.github/workflows/main.yml#L42

regarding this bit of code, this very much needs to be brought up to date - the Stanc3 compiler has added a bunch of options since this was written.

the Stanc3 compiler options that don't result in C++ outputs are not exposed in CmdStanPy - those are for the Stanc3 devs working on the language - the purpose of the `compile` function in CmdStanPy is to produce a model executable.
