### ISSUE TITLE
Move from travis-ci.org to travis-ci.com

### ISSUE THREAD

**Issue by ahartikainen** [stan-dev/cmdstanpy#314]
#### Summary:

We hit the api rate limit. This can be fixed with travis-ci.com

See https://jamescooke.info/migrating-open-source-projects-on-travis-ci-to-fix-github-api-limit-problems.html

**Comment by mitzimorris** [comment]
are other stan-dev repos affected as well?   @jgabry @serban-nicusor-toptal

**Comment by serban-nicusor-toptal** [comment]
Hey, 

I went through them and I only saw the one on [cmdstanpy here](https://travis-ci.org/github/stan-dev/cmdstanpy/jobs/736150248) do that.
This may happen in the future again, as per the article above it's shared between all rather than dedicated/org.
I've moved cmdstanpy to `travis-ci.com` I've also restarted the job that failed [here](https://travis-ci.com/github/stan-dev/cmdstanpy/builds/190603454). 
Please let me know if I should transfer any other active project we have using Travis. I hope it's all good and needs no further changes, if the old checks still show up in a pr try to push a commit and it should reset it.

**Comment by ahartikainen** [comment]
Great!

**Comment by jgabry** [comment]
> are other stan-dev repos affected as well? @jgabry @serban-nicusor-toptal

We moved to github actions for cmdstanr instead of travis, so cmdstanr isn't affected by this.
