### ISSUE TITLE
FR: Support complete installation via conda

### ISSUE THREAD

**Issue by WardBrian** [stan-dev/cmdstanpy#395]
#### Summary:
[conda](https://docs.conda.io/en/latest/index.html) is a package manager which specializes in creating Python environments which also require non-Python dependencies. This serves as a perfect fit for this kind of project, and would make installation (particularly on Windows) much easier without the need for something like `install_cxx_toolchain` or `install_cmdstan`, neither of which live 100% happily in a conda environment at the moment.

#### Description:
conda allows you to install both Python and other dependencies in a sandboxed way. This is particularly helpful on Windows, if the user doesn't want  mingw32's many binaries on their PATH.

Currently, you can install everything you need in a sandboxed way like this:

```powershell
conda create -n cmdstan python=3.9
conda activate cmdstan
# this is the equivalent of installing the toolchain, but it handles all environment variables (including PATH) for you
conda install -c msys2 m2-base m2-findutils m2w64-toolchain
# this seems to be unofficial? https://github.com/conda-forge/cmdstanpy-feedstock
conda install -c conda-forge cmdstanpy
# this is probably the least nice part, installing in a subfolder of the environment to keep it all tidy
python -m cmdstanpy.install_cmdstan -d "C:\ProgramData\Miniconda3\envs\cmdstan\cmdstan"
# this tells cmdstanpy where we installed it, and will be added or removed when the environment is activated/deactivated
conda env config vars set CMDSTAN="C:\ProgramData\Miniconda3\envs\cmdstan\cmdstan\cmdstan-2.27.0"
conda activate cmdstan
# good to go
```

Ultimately, I think it would be relatively easy to get this down to just
```powershell
conda create -n cmdstan python=3.9
conda activate cmdstan
conda install cmdstanpy
```
IF cmdstan itself had a conda build package created and the proper dependencies were all set in each package. I wasn't sure if this issue would belong here or in that repo, so I'm starting here.

#### Additional Information:
This seems like it was previously discussed in #7. I think that the `install_cxx_toolchain` command is useful for Windows folks using pip, but I see no reason why both couldn't be supported. I know this would be very helpful on Windows, users of other platforms may still find it simpler to have cmdstan installed as part of the environment process, and this would allow multiple versions to be used on the same machine side-by-side relatively easily. 

The current conda-forge feedstock for cmdstanpy is maintained by @maresb, who may have some thoughts on this

**Comment by maresb** [comment]
Hello there @WardBrian! Indeed I do have thoughts on getting `cmdstan` running with `mamba`. I made the `cmdstanpy` package in part because I wanted an installer for `cmdstan` within a Conda environment.

I was working on [this pull request](https://github.com/conda-forge/staged-recipes/pull/15203) to add `cmdstan` to conda-forge, but unfortunately no matter what I tried I always got a segfault. It's very frustrating; I don't understand why, and I don't understand so much about segfaults in general. I don't know how to go about fixing it. I'd be delighted if someone could pick up where I left off and get it running.

I'm happy to add anyone as collaborator on my fork, or whatever else would need to be done to get some help.

Finally, there's a very helpful [conda-forge gitter channel](https://gitter.im/conda-forge/conda-forge.github.io). Perhaps I should have already asked for help there, but I didn't feel like I got far enough to where I felt good about asking.

**Comment by mitzimorris** [comment]
this sounds absolutely reasonable!  @WardBrian, when you get to NYC, it would be good to set up an IRL meeting to work this out.  online would be great too. easy install is first priority here, and anything we can do to offer more better and easier options would be great.

**Comment by maresb** [comment]
By the way, I think a killer feature of the Conda ecosystem is the relatively new `micromamba` tool by @wolfv. Micromamba is a bare-bones reimplementation of `conda` in C++. Most interestingly, it allows one to create Conda environments in which Python is absent. (Normally Python is required as a dependency of the `conda` command, so historically, Conda environments were always Python environments, but no longer!) This means that via `micromamba` you get all the dependency management advantages of the Conda/conda-forge ecosystem, without all the bloat of Python. (This is especially useful for Docker and such, where one wants environments which are as lean as possible.)

**Comment by WardBrian** [comment]
Good to hear @maresb - I have relatively little experience with conda-forge besides as a user, but I can try to give it a go soon based on the work you've started.

I agree with @mitzimorris, I think this is good as an addition to the installation tools in the package, not a replacement, so the use of `install_cmdstan` in the conda build script seems like the right first attempt to me. That said, we might want to consider down the line that some users of conda/cmdstan may be trying to use it in R, so requiring python for the install is perhaps ill-advised especially with mamba making this dependency optional, as you point out. A more traditional build.sh/bld.bat setup (which call make/mingw32-make respectively) would probably be a good idea in the long term

**Comment by maresb** [comment]
I gave you both access to my `staged-recipes` fork so that we can collaborate on my PR.

With conda-forge, virtually everything is driven by `meta.yaml`. If you look at [my commit history](https://github.com/conda-forge/staged-recipes/pull/15203/commits) I tried both compiling directly and using `install_cmdstan`. I'm sure that this will be much easier for someone more experienced with C++ debugging that me. I don't know so well myself what I'm doing. For the more advanced stuff, there's a lot of great info in the [conda-forge knowledge base](https://conda-forge.org/docs/maintainer/knowledge_base.html). And then Gitter is usually very helpful in case you get stuck.

I also recommend looking at the [build logs](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=333771&view=results) to see the various results for linux/mac/win.

I think that should give you all the resources you need to make progress. Let me know if I can help. I'm very grateful for the interest! I was afraid my effort would die out.

**Comment by WardBrian** [comment]
I had a look @maresb, and it seems to me like the segfault is occuring during the test of stanc -- this makes no sense to me, ad cmdstan ships pre-compiled instances of stanc. Is it possible this is a docker issue?

**Comment by WardBrian** [comment]
Hi @maresb - I've gotten it to compile on the Linux docker instance and run the bernoulli example program. MacOS and Windows are still having some various problems, but I'd appreciate some fresh eyes. 

I think the remaining issues are setting up activate/deactivate scripts to set the CMDSTAN environment variable (see [1](https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#setting-environment-variables), [2](https://docs.conda.io/projects/conda-build/en/latest/resources/activate-scripts.html)), ironing out the other OSes, and testing a full install against cmdstanpy.

**Comment by maresb** [comment]
@conda-forge/help-c-cpp, we are struggling quite a lot with https://github.com/conda-forge/staged-recipes/pull/15203. Any chance of getting some help?

Thanks so much @WardBrian for the progress so far.

**Comment by WardBrian** [comment]
To keep the updates in one place, this effort is currently passing the CI tests on all three major platforms. I've been having a difficult time getting someone to review it however, maybe @maresb needs to be the requester there?

**Comment by maresb** [comment]
I just called for review, thanks for following up!

**Comment by maresb** [comment]
Wow, cmdstan [vendors all of boost](https://github.com/stan-dev/math/tree/0f9df690aa3db1be9d6d8505b500da2824ff8aea/lib) (not to mention all the other libraries), adding 162 MB. I imagine that there are good reasons, but that makes cmdstan not so lightweight.

As for the conda package, just because something is included in the tarball doesn't strictly mean that you have to include it in the conda package. You could theoretically replace it with a `meta.yaml` dependency and delete the vendored package during build... but you've already done so much work, so let's see what @ **conda-forge/help-c-cpp** has to say.

**Comment by WardBrian** [comment]
Unfortunately that's impossible on Windows, because of the reliance on mingw64's gcc, while all of the libraries available on conda-forge use MSVC on Windows. 

If cmdstan could be built with MSVC, we could use all of conda's pre-built libraries, but they're not compatible across compiler families. @mitzimorris  - do you happen to know why MSVC can't be used?

**Comment by ahartikainen** [comment]
There was some C++ template stuff that doesn't work -> no vectors or matrices

**Comment by WardBrian** [comment]
Alright, so using the pre-built conda libraries is a nonstarter then. I'm pretty sure there's no problem with how it's currently set up license-wise, we will just have to see what the conda-forge maintainers think.

**Comment by WardBrian** [comment]
@maresb - I believe you can at least check off the "License file is packaged" task on the PR, if not the other two as well (the licenses are all in the tarball, so I believe they also count as "packaged").

**Comment by maresb** [comment]
@WardBrian thanks for clarifying the situation with MSVC vs mingw64. (Even though I don't understand on the technical level.)

I checked off "License file is packaged". I don't want to check off "Package does not vendor other packages" because it does vendor all those libraries. I'm hoping that the maintainers will make an exception for us when we explain the situation. In any case, I don't think the lack of check marks will hold up the review, but rather should assist with a review to make sure we are doing everything as well as possible. (For the licenses for static libraries, I understand neither what is and isn't statically linked nor exactly what conda-forge means by "packaged" but if you're convinced it's correct then I could check off also that.)

I haven't ever used cmdstan directly, so I'm quite ignorant, but I assume that compiling the models requires all of those source libraries to be present, and compiled libraries wouldn't suffice?

I was about to suggest posting to Gitter to request a review, but I just noticed that you already posted. Unfortunately getting a response there is very hit-or-miss. If there's no response I'd try posting again after a day with a few more details (package name, mention that it's a tool for compiling Bayesian models in C, mention that you and others have been working for several weeks on the recipe).

For context 95% of the recipes I've made are for pure Python packages, and about half of those can be created within 10 minutes as noarch, and the other half might require an hour or two of fiddling around, so this effort here is rather extraordinary.

**Comment by mitzimorris** [comment]
> that compiling the models requires all of those source libraries to be present, and compiled libraries wouldn't suffice?

in certain situations, yes.  the CmdStanPy and CmdStanR wrapper interfaces allow the user to pass in C++ compiler flags, some of which might require recompiling the source libraries.  cf discussion here:  https://discourse.mc-stan.org/t/cmdstanr-how-to-set-c-flags/19104/4
