### ISSUE TITLE
generate_quantities function does not require complete set of parameters

### ISSUE THREAD

**Issue by NicholasCowie** [stan-dev/cmdstanpy#454]
#### Summary:
Hi All,
The generate_quantities function does not require complete set of parameters. It appears that removal of parameters defined at the end of the parameter block does raise an error.

#### Description:
I'm using the generate quantities function in cmdstanpy to do posterior predictive checks, often there are experiment specific parameters that are not required in the posterior predictive check as I use these draws on experiments that are not conducted yet. I tried the following model code with the associated generated quantities model code.

**Model Block**
```
data {
  int<lower=1> N_data;
  array[N_data] int<lower=0,upper=1> y;
}

parameters {
  real<lower=0.1,upper=1.1> theta_z;
  real alpha;
}

transformed parameters {
  real<lower=0, upper=1> theta = theta_z - 0.1;
}

model {
  alpha ~ normal(0,1);
  theta ~ beta(1, 1);
  y ~ bernoulli(theta);
}
```

**Generated Quantities Model Code**
```
data {
  int<lower=1> N_posterior;
}

parameters {
  real<lower=0.1,upper=1.1> theta_z;
}

transformed parameters {
  real<lower=0, upper=1> theta = theta_z - 0.1;
}

generated quantities {
  array[N_posterior] int<lower=0,upper=1> y_gen;
  for (n in 1:N_posterior)
    y_gen[n] = bernoulli_rng(theta);
}
```
This code managed to run despite not having the alpha parameter defined in the model block. However when swapping the order of parameters in the model block to:
```
parameters {
  real alpha;
  real<lower=0.1,upper=1.1> theta_z;
}
```
the above generated quantities model did not run. I should probably rename a new set of parameters for my case, but I do think this is some pretty interesting behaviour.

#### Current Version:
Tried in 2.27.0 and an experimental branch of 2.26 (the adjoint-solver-v2 one)
cmstanpy v0.9.77

**Comment by mitzimorris** [comment]
not unexpected at all - but perhaps we should try to make it clearer that both models need identical parameters blocks in order to work correctly.

the `generate_quantities` method uses the (total) number of parameters defined in the generate_quantities model,
and grabs that many columns from the fitted_params CSV file.  so it used the values for `alpha`, which, probably were not in the range 0.1 to 1.1.

**Comment by mitzimorris** [comment]
closing this, with the full acknowledgement that `generate_quantities` method is a hack - useful, yes, but a hack nonetheless.

**Comment by NicholasCowie** [comment]
Ahh okay, that explains a lot about my other attempts. So it just grabs the columns from the csvs and assumes the structure is identical to the parameter block. And yes, noted that is definitely a hack and will not be relying on this behaviour for the future.

Cheers for the clarification

**Comment by mitzimorris** [comment]
perhaps

**Comment by bob-carpenter** [comment]
Thanks for submitting the issue, @NicholasCowie.  If you're trying to economize what you save, you should be able to run standalone generated quantities by removing parameters and matching columns from the .csv. 

I don't know if cmdstan lets you omit parameters from the output directly---RStan does.

> (@mitzimorris) but perhaps we should try to make it clearer that both models need identical parameters blocks in order to work correctly

Yes, please.  The doc should indicate that the model parameters need to match in name and order an initial segment of the csv parameters in order to work properly.
