### ISSUE TITLE
1.0 Release

### ISSUE THREAD

**Issue by WardBrian** [stan-dev/cmdstanpy#475]
This is intended as the final item in the 1.0 release project

## Oct. 19
- [x] Run release scripts for version `1.0.0rc1`
- [x] 1.0.0rc1 on Conda

## Early November

After #436 

- [x] Run release scripts for version `1.0.0rc2`
- [x] 1.0.0rc2 on Conda

## One week later
- [x] Run release scripts for version `1.0.0`
- [x] Verify doc updated on mc-stan.org and readthedocs.io
- [x] (for Brian) update Conda after builds have propagated. Include tqdm as a dependency
- [x] (optional) Post on forums/columbia stats blog
- [x] (later) We should let Arviz/fbprophet teams know about stabilization of the API and changes. Arviz seemed more affected when I checked. There is additionally [this list of dependent packages](https://libraries.io/pypi/cmdstanpy/dependents)

**Comment by serban-nicusor-toptal** [comment]
Hey @WardBrian can I do this now or should I wait for the others (math, stan, cmdstan ) release first ?

**Comment by mitzimorris** [comment]
excellent plan - let's do it!

**Comment by serban-nicusor-toptal** [comment]
rtd build is done: https://cmdstanpy.readthedocs.io/en/v1.0.0rc1/

**Comment by WardBrian** [comment]
Note: We will now be doing a rc2 and delaying the release until #436

**Comment by serban-nicusor-toptal** [comment]
Please let me know if/when I need to run the rc2 or if I can help with anything here.

**Comment by WardBrian** [comment]
Thanks Nic, will do.  It will probably be at least a couple days or so to get #436 good to go

**Comment by WardBrian** [comment]
So @mitzimorris how do you feel about cutting a RC2? If we mostly have doc left to write we can do that during the release period, but if we think there are more changes could be good to wait?

**Comment by mitzimorris** [comment]
Yes!!!!
please, let's cut a release and announce on Discourse

**Comment by mitzimorris** [comment]
@ahartikainen - noticed Arviz issue w/ cmdstanpy - is there anything needed from our side?  https://github.com/arviz-devs/arviz/issues/1646#issuecomment-971660864

**Comment by WardBrian** [comment]
rc2 is out on pypi, conda will follow (probably tomorrow)

**Comment by mitzimorris** [comment]
slouching towards Beta - https://discourse.mc-stan.org/t/cmdstanpy-1-0-0rc2/25337

**Comment by WardBrian** [comment]
On conda now

**Comment by WardBrian** [comment]
https://github.com/stan-dev/cmdstanpy/issues/499 is simple but important enough that I think we should cut rc3 when it's patched. It won't need a conda version, as it only effects non-conda installs.

**Comment by WardBrian** [comment]
Do we want to release 1.0 this week? Latest rc will have been out for 2 weeks on Thursday

**Comment by mitzimorris** [comment]
yes!!!

**Comment by mitzimorris** [comment]
@rok-cesnovar @jgabry - OK if we do a 1.0 CmdStanPy release tomorrow?
where is CmdStanR at?

**Comment by WardBrian** [comment]
I think we should do it tomorrow (Dec 2) so that the RC had a full 2 weeks. 

We should also note in the release forum/blog post that 1.0.0 is supported on Python 3.6 through 3.10, but future versions will require 3.7 (I think it's pretty unlikely we fit in a 1.1 in the next 20 days before 3.6 hits EOL)

**Comment by WardBrian** [comment]
Here goes nothing https://github.com/stan-dev/cmdstanpy/actions/runs/1531682007

**Comment by mitzimorris** [comment]
here's a blurb - it's a bit dry:

Announcing version 1.0 of CmdStanPy!

CmdStanPy is now available via Conda Forge: https://anaconda.org/conda-forge/cmdstanpy
and PyPi: https://pypi.org/project/cmdstanpy/

Reasons to use CmdStanPy:

1. Runs with latest Stan release

2. Easy to install:  CmdStanPy can automatically CmdStan and the underlying C++ toolchains

3. Scalable:  can fit big models and big dataset - if CmdStan can fit a model and dataset, so can CmdStanPy.

4. Cross-platform:  runs on Linux, macOS, and Windows.

5. Non-restrictive lisence: BSD-3 license: https://github.com/stan-dev/cmdstanpy/blob/develop/LICENSE.md


CmdStanPy provdes access to the Stan compiler, inference algorithms, and diagnostics.
It supports both development and production workflows.
Because model development and testing may require many iterations, the defaults favor development mode and therefore output files are stored on a temporary filesystem. Non-default options allow all aspects of a run to be specified so that scripts can be used to distributed analysis jobs across nodes and machines.
It is also well-suited for teaching and learning Stan.

**Comment by WardBrian** [comment]
I think the blurb is good! I'd also add a link to the repo and docs homepage
