### ISSUE TITLE
Cmdstanpy ValueError with multiprocess

### ISSUE THREAD

**Issue by alexhallam** [stan-dev/cmdstanpy#504]
#### Summary:

I am using cmdstanpy in a package I put together.

I am able to run the program in sequence, but when I try to run in parallel I get the following error.

> ValueError: line 7977: bad draw, expecting 18 items, found 14

#### Description:

Please see this thread. https://discourse.mc-stan.org/t/cmdstanpy-valueerror-with-multiprocess/25553

It would be nice if cmdstanpy was more friendly to multiprocess.

**Comment by WardBrian** [comment]
Could you put together a small code example that recreates the issue you’re experiencing? The error you get sounds like what I would expect if the draws file was being overwritten while it was being read, which is definitely possible in a multi process setup

**Comment by alexhallam** [comment]
This is the only example I have available at this second. I am happy to zoom in a little more with a more minimal example this weekend.

```py
import numpy as np
import pandas as pd
import tablespoon as tbsp
from multiprocessing import Pool

# pull and clean data
# columns must have the columns "ds" and "y"
# this time series is at the daily level. the seasonality is 7 days.
install_cmdstan()
def pred_things(df):
    sn = tbsp.Snaive()
    df_pred = sn.predict(df, horizon=10, frequency="D", lag=7, uncertainty_samples=8000)
    return df_pred


df_ca = (
    pd.read_csv("https://storage.googleapis.com/data_xvzf/m5_state_sales.csv")
    .query("state_id == 'CA'")
    .rename(columns={"date": "ds", "sales": "y"})
)
df_tx = (
    pd.read_csv("https://storage.googleapis.com/data_xvzf/m5_state_sales.csv")
    .query("state_id == 'TX'")
    .rename(columns={"date": "ds", "sales": "y"})
)
list_df = [df_ca, df_tx]
# this works
list(map(pred_things, list_df))
# this does not
with Pool() as P:
    parallel_prod = list(P.map(pred_things, list_df))

print(parallel_prod)
```

The core of this method is coded here https://github.com/alexhallam/tablespoon/blob/61d23c0f44e418e9b840a9356be833f2f992bfa4/tablespoon/forecasters.py#L56-L62

**Comment by mitzimorris** [comment]
I posted a reply on Discourse:  https://discourse.mc-stan.org/t/cmdstanpy-valueerror-with-multiprocess/25553/4?u=mitzimorris

I think all you need to do is supply a chain_id to the call to the sampler, and make sure that that chain id is unique.  the chain_id is part of the CSV file name, so it will prevent files from getting overwritten.

**Comment by WardBrian** [comment]
Resolved on forums using `chain_id`

**Comment by fcostin** [comment]
(i'm rfc from the discourse thread)

I suspect there are two potential errors with @alexhallam's application code:

1. CSV output files being overwritten by the n CmdStanModel instances during sampling.
2. many CmdStanModel instances are being constructed in parallel in the same directory, with the same hpp and exe file names 

The reported symptom sounds like the first error.  @mitzimorris 's suggestion to use `chain_id` looks like a great, simple way to fix it.
 
Re the second potential error, of which we don't see any symptoms:  if many CmdStanModel instances are being constructed in parallel, trying to write to the same hpp and exe file names, then the application code as-is will probably work correctly 90% or 99.9% of the time, it'll only fail depending exactly on how parallel processes get scheduled.

Race condition for model compilation could be avoided by reworking the application code to follow @mitzimorris pattern shared in the discourse thread for sampling from a previously compiled stan model in a cluster:

(a) compile the model once, store the location of the model's exe_file
(b) then n times in parallel, create CmdStanModel instances passing in the exe_file location from the previous and call sample with a unique chain_id value

Another way to guard against race conditions in parallel model compilation could be to change the application code to add explicit locks around the parts that call `CmdStanModel` (but not around the sampling bit) so that at most one process is allowed to attempt to compile any given Stan model. Maybe could use `multiprocessing.Lock` : https://docs.python.org/3/library/multiprocessing.html#sharing-state-between-processes

( these are all changes in @alexhallam 's application code, not changes in cmdstanpy library itself )

**Comment by mitzimorris** [comment]
@fcostin, re:

> Regarding the second potential error, that I suspect exists, of which we don't see any symptoms: if many CmdStanModel instances are being constructed in parallel, trying to write to the same hpp and exe file names on disk, then the application code as-is will probably work correctly 90% or 99.9% of the time, it'll only fail depending exactly on how parallel processes get scheduled.

if the CmdStanModel instances were all trying to compile the model at the same time, yes, this is a possibility, but my guess is that in this case, there was already an exe file newer than the stan file, so this didn't arise.  you could proably make this happen by specifying `compile='force'` (cf https://mc-stan.org/cmdstanpy/api.html#cmdstanpy.CmdStanModel).

**Comment by alexhallam** [comment]
I got some help from a new friend. The solution was to use tempfile. From what I understand each core will generate new names from each temp directory name.

https://github.com/alexhallam/tablespoon/blob/f51c84db4c1a6b423fbc173e40fb09c49f9220c8/tablespoon/forecasters.py#L72-L80
